### ISSUE TITLE
invalid type /metadata/TaskContext

### ISSUE THREAD

**Issue by annaborn** [rock-core/tools-logger#4]
In a fresh boostrapping of the rock-rc, the following error occurs in the package tools/logger:

```
/usr/bin/ruby1.9.1 /home/dfki.uni-bremen.de/aborn/DFKI/ROCK_RC/tools/orogen/bin/orogen --corba --extensions=metadata_support --import=std --no-rtt-scripting --parallel-build=4 --transports=corba,mqueue,typelib --type-export-policy=used logger.orogen
    in directory /home/dfki.uni-bremen.de/aborn/DFKI/ROCK_RC/tools/logger
    logger.orogen:10: invalid type /metadata/TaskContext: cannot find /metadata/TaskContext in registry (OroGen::ConfigError)
```

**Comment by doudou** [comment]
There's still a bug in the package sets, that allows you to have the flavor set to 'master' while you are on the release. Only 'stable' is supported there.

I've just created an issue about it: https://github.com/rock-core/package_set/issues/39

Please switch the flavor to stable by running

~~~
autoproj reconfigure
~~~

**Comment by goldhoorn** [comment]
should be fixed in HEAD
